---
# TODO: `systemctl unmask tmp.mount` to make /tmp tmpfs (`cvmfs_server import`
# fails if /tmp is xfs, although for some reason was fine on the PSU stratum 0
# w/ xfs /tmp).

- name: Determine whether -p flag is needed for cvmfs_server mkfs or import
  ansible.builtin.set_fact:
    cvmfs_config_apache_flag: "{{ '-p' if not cvmfs_config_apache else '' }}"

- name: Include initial OS-specific tasks
  ansible.builtin.include_tasks: init_{{ ansible_os_family | lower }}.yml
  vars:
    _cvmfs_role: gateway
    _cvmfs_upgrade: "{{ cvmfs_upgrade_server }}"

- name: Include key setup tasks
  ansible.builtin.include_tasks: keys.yml

- name: Include filesystem tasks
  ansible.builtin.include_tasks: filesystem.yml

- name: Include Apache tasks
  ansible.builtin.include_tasks: apache.yml

- name: Include firewall tasks
  ansible.builtin.include_tasks: firewall.yml
  vars:
    _cvmfs_http_ports: "{{ cvmfs_gateway_http_ports }}"
  when: cvmfs_manage_firewall

- name: Include firewall tasks
  ansible.builtin.include_tasks: firewall.yml
  vars:
    _cvmfs_gateway_ports: "{{ cvmfs_gateway_ports }}"
  when: cvmfs_manage_firewall

- name: Create repositories
  ansible.builtin.command: |
    /usr/bin/cvmfs_server mkfs {{ cvmfs_config_apache_flag }} -o {{ item.owner | default('root') }} -f {{ cvmfs_union_fs }} {{ item.repository }}
  args:
    creates: /srv/cvmfs/{{ item.repository }}
  with_items: "{{ cvmfs_repositories }}"
  notify:
    - Restart apache

- name: Ensure repositories are imported
  ansible.builtin.command: |
    /usr/bin/cvmfs_server import -r {{ cvmfs_config_apache_flag }} -o {{ item.owner | default('root') }} -f {{ cvmfs_union_fs }} {{ item.repository }}
  args:
    creates: /etc/cvmfs/repositories.d/{{ item.repository }}
  with_items: "{{ cvmfs_repositories }}"
  notify:
    - Restart apache

- name: Include repository server options tasks
  ansible.builtin.include_tasks: options.yml
  vars:
    _cvmfs_repo_option_key: server

- name: Include repository client options tasks
  ansible.builtin.include_tasks: options.yml
  vars:
    _cvmfs_repo_option_key: client

- name: Create the API repos config
  ansible.builtin.template:
    src: repo.json.j2
    dest: "/etc/cvmfs/gateway/repo.json"
    mode: "0644"
  loop: "{{ cvmfs_repositories_api }}"

- name: Create the API key filesystem
  ansible.builtin.template:
    src: api-key.gw.j2
    dest: /etc/cvmfs/keys/'{{ item.repository }}'.gw
    mode: "0600"
  loop: '{{ cvmfs_repositories_api }}'
  notify:
    - Restart gateway service