---
- name: Create gateway repos for repository publishing access (stratum 0)
  template:
    src: repos.json.j2
    dest: "/etc/cvmfs/gateway/repo.json"
    force: no
    owner: root
    group: root
    mode: '644'

- name: Enable gateway service (stratum 0)
  service:
    name: cvmfs-gateway
    enabled: yes
    state: started