---

- name: Ensure distribution is LTS or cvmfs_apt_distribution is set
  assert:
    that: >-
      (ansible_distribution == 'Ubuntu' and 'LTS' in (ansible_lsb.distribution | default(''))) or
      (ansible_distribution == 'Debian' and ansible_distribution_version != 'n/a') or
      (cvmfs_apt_distribution is defined)
    fail_msg: "Unsupported distribution: {{ ansible_distribution }} {{ ansible_distribution_release }}, please set cvmfs_apt_distribution"
    success_msg: "Distribution OK"

- name: Install apt dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates

- name: Make sure /etc/apt/keyrings is present
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install CernVM apt key
  ansible.builtin.get_url:
    url: "{{ cvmfs_apt_repository_key }}"
    dest: /etc/apt/trusted.gpg.d/cernvm.gpg
    mode: '0644'

- name: Configure CernVM apt repository
  ansible.builtin.apt_repository:
    filename: cernvm.list
    mode: '0644'
    repo: "{{ cvmfs_apt_repository }}"

- name: Install CernVM-FS packages and dependencies (apt)
  ansible.builtin.apt:
    name: "{{ cvmfs_packages[_cvmfs_role] }}"
    state: "{{ 'latest' if _cvmfs_upgrade else 'present' }}"
